import test from 'node:test';
import assert from 'node:assert/strict';
import { prepareReview, selectRules, updateActiveRules, validateReview, RULE_BY_ID } from '../src/engine.mjs';

test('authentication task loads security/testing and excludes safety-only',()=>{ const r=selectRules({taskType:'authentication'}); assert.ok(r.rules.some(x=>x.category==='security')); assert.ok(r.rules.some(x=>x.category==='testing')); assert.equal(r.active_rule_ids.some(id=>{const rr=RULE_BY_ID.get(id); return rr.scope.includes('safety_critical')&&!rr.scope.includes('general')}),false); });
test('dynamic update is additive and adds dependency rules',()=>{ const i=selectRules({taskType:'feature'}); const u=updateActiveRules(i.active_rule_ids,{triggers:['dependency_added'],categories:['dependency','security']}); assert.ok(u.active_rule_ids.length>=i.active_rule_ids.length); assert.ok(u.added_rules.some(x=>x.category==='dependency')); for(const id of i.active_rule_ids) assert.ok(u.active_rule_ids.includes(id)); });
test('package file reveals dependency rules at review time',()=>{ const i=selectRules({taskType:'feature'}); const r=prepareReview(i.active_rule_ids,['package.json']); assert.ok(r.dynamically_added_rule_ids.length>0); assert.ok(r.checklist.some(x=>x.category==='dependency')); });
test('review gate rejects missing must rules',()=>{ const s=selectRules({taskType:'bugfix'}); const r=validateReview(s.active_rule_ids,[]); assert.equal(r.complete,false); assert.ok(r.missing_must_rules.length>0); });
test('review gate requires evidence for pass',()=>{ const s=selectRules({taskType:'bugfix'}); const id=s.active_rule_ids.find(id=>RULE_BY_ID.get(id).severity==='must'); const r=validateReview([id],[{rule_id:id,status:'pass'}]); assert.equal(r.complete,false); assert.equal(r.invalid_evidence.length,1); });
test('review gate rejects unknown items',()=>{ const r=validateReview([], [{rule_id:'UNKNOWN',status:'pass',evidence:'x'}]); assert.equal(r.complete,false); assert.deepEqual(r.unknown_review_items,['UNKNOWN']); });
test('review can complete with evidence',()=>{ const s=selectRules({taskType:'bugfix'}); const ids=s.active_rule_ids.filter(id=>RULE_BY_ID.get(id).severity==='must').slice(0,3); const items=ids.map(rule_id=>({rule_id,status:'pass',evidence:'Verified against changed diff and relevant test output.'})); const r=validateReview(ids,items); assert.equal(r.complete,true); });
